name: torsional_diffusion
channels:
  - conda-forge
  - defaults
  - pytorch
  - pyg
dependencies:
<<<<<<< HEAD
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.12=h4ab18f5_0
  - attr=2.5.1=h166bdaf_1
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=hbb29018_2
  - certifi=2024.7.4=pyhd8ed1ab_0
  - chardet=5.2.0=py39hf3d152e_1
  - contourpy=1.2.1=py39h7633fee_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - dftd4=3.6.0=hf49bc11_0
  - expat=2.6.2=h59595ed_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py39hcd6043d_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - glib=2.80.3=h8a4344b_1
  - glib-tools=2.80.3=h73ef956_1
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.0.3=py39h3d6467e_0
  - gst-plugins-base=1.24.5=hbaaba92_0
  - gstreamer=1.24.5=haf2f30d_0
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libblas=3.9.0=23_linux64_openblas
  - libboost=1.84.0=hba137d9_3
  - libboost-python=1.84.0=py39h1eb36c5_4
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=23_linux64_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.8=default_h9def88c_1
  - libcups=2.3.3=h4637d8d_4
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.80.3=h8a4344b_1
  - libgomp=14.1.0=h77fa898_1
  - libgpg-error=1.50=h4f305b6_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=23_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.8=h8b73ec9_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - librdkit=2024.03.5=h79cfef2_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libsystemd0=255=h3516f8a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=h4ab18f5_1
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib=3.9.1=py39hf3d152e_0
  - matplotlib-base=3.9.1=py39hd75cb13_0
  - mctc-lib=0.3.2=h3b12eaf_0
  - mpg123=1.32.6=h59595ed_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=h59595ed_0
  - nspr=4.35=h27087fc_0
  - nss=3.102=h593d115_0
  - numpy=2.0.1=py39h2fd3214_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py39hfc16268_1
  - pcre2=10.44=h0f59acf_0
  - pillow=10.4.0=py39h16a7006_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - ply=3.11=pyhd8ed1ab_2
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=17.0=hb77b528_0
  - pyaml=24.7.0=pyhd8ed1ab_0
  - pycairo=1.26.1=py39h0d2dcfc_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py39h52134e7_5
  - pyqt5-sip=12.12.2=py39h3d6467e_5
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h320f8da_24
  - rdkit=2024.03.5=py39hc1ff0a3_1
  - readline=8.2=h8228510_1
  - reportlab=4.2.2=py39hd3abc70_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - setuptools=71.0.4=pyhd8ed1ab_0
  - simple-dftd3=1.0.0=hd59d2e7_0
  - sip=6.7.12=py39h3d6467e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.31=py39hd3abc70_0
  - tblite=0.3.0=hf49bc11_1
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - toml-f=0.4.2=hd8f1df9_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4.1=py39hd3abc70_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xtb=6.6.1=hf49bc11_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - beautifulsoup4==4.12.3
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.2
    - debugpy==1.8.5
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - e3nn==0.5.1
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - filelock==3.15.4
    - frozenlist==1.4.1
    - fsspec==2024.6.1
    - gdown==5.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - idna==3.7
    - importlib-metadata==8.4.0
    - ipykernel==6.29.5
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.13
    - lark-parser==0.12.0
    - markupsafe==2.1.5
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - multidict==6.0.5
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu12==12.1.105
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - parso==0.8.4
    - pexpect==4.9.0
    - platformdirs==4.3.3
    - prompt-toolkit==3.0.47
    - protobuf==5.28.2
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py3dmol==2.4.0
    - pyg-lib==0.4.0+pt23cu121
    - pygments==2.18.0
    - pysocks==1.7.1
    - pyzmq==26.2.0
    - requests==2.32.3
    - rmsd==1.5.1
    - rustworkx==0.15.1
    - scikit-learn==1.5.1
    - scipy==1.13.1
    - sentry-sdk==2.16.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - soupsieve==2.5
    - spyrmsd==0.8.0
    - stack-data==0.6.3
    - sympy==1.13.1
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - torch==2.3.0
    - torch-cluster==1.6.3+pt23cu121
    - torch-geometric==2.5.3
    - torch-scatter==2.1.2+pt23cu121
    - torch-sparse==0.6.18
    - torch-spline-conv==1.2.2
    - torchani==2.2.4
    - tqdm==4.66.4
    - traitlets==5.14.3
    - triton==2.3.0
    - urllib3==2.2.2
    - wandb==0.18.3
    - wcwidth==0.2.13
    - widgetsnbextension==4.0.13
    - yarl==1.9.4
=======
  - python=3.9
  - rdkit
  - pyaml
  - matplotlib
>>>>>>> parent of a61fbf4 (update env packages)
